server:
  port: '8090'
  mode: 'release'
  defaultPageSize: 20 # 默认分页条数
  maxPageSize: 500    # 最大分页条数
  tokenExpire: 600000 # token过期时间
  jwtSecret: 'LIXLolf0ZJ8qalcwh5FQi5xrzjJQHLpy'
log:
  debug: true
  fileName: 'server.log' # 日志文件名称
  dirPath: '/Users/artist/Program/go/start-go-api' # 日志默认存放目录
mysql:
  host: '127.0.0.1'
  port: '3306'
  user: 'root'
  password: '123456'
  database: 'start-go-api'
redis:
  host: '127.0.0.1'
  password: ''
  dbNum: 0
