definitions:
  entities.PageReq:
    properties:
      page:
        type: integer
      pageSize:
        type: integer
      searches:
        items:
          $ref: '#/definitions/global.Search'
        type: array
      total:
        type: integer
    type: object
  entities.SysApiServiceCreateReq:
    properties:
      description:
        type: string
      group:
        type: string
      is_use:
        type: integer
      method:
        type: integer
      path:
        type: string
      role_id:
        type: integer
    required:
    - description
    - group
    - method
    - path
    - role_id
    type: object
  entities.SysMenuServiceReq:
    properties:
      icon:
        type: string
      is_use:
        type: integer
      level:
        type: integer
      name:
        type: string
      pid:
        type: integer
      sort:
        type: integer
      unique_key:
        type: string
    required:
    - is_use
    - level
    - name
    - pid
    - unique_key
    type: object
  entities.SysRoleMenuServiceCreateReq:
    properties:
      menu_ids:
        items:
          type: integer
        type: array
      role_id:
        type: integer
    type: object
  entities.UserServiceCreateReq:
    properties:
      nickname:
        type: string
      password:
        type: string
      phone:
        type: string
      status:
        type: integer
    required:
    - nickname
    - password
    - phone
    - status
    type: object
  entities.UserServiceTokenReq:
    properties:
      password:
        type: string
      phone:
        type: string
    type: object
  entities.UserServiceUpdateReq:
    properties:
      id:
        type: integer
      nickname:
        type: string
      phone:
        type: string
      status:
        type: integer
    type: object
  global.Search:
    properties:
      action:
        description: '查询方式 如: equals 表示 = | like 表示 LIKE | in 表示 IN'
        type: string
      column:
        description: '字段名称 如: nickname | phone'
        type: string
      needle:
        description: '所需条件 如: equals时对应等于的那个值 | like时表示那个关键词 | in时表示一个用逗号分隔的字符串 "2,3,4,5,6"'
        type: string
    type: object
  response.JsonResponse:
    properties:
      code:
        description: 错误码
        type: integer
      data:
        description: 返回数据(业务接口定义具体数据结构)
      message:
        description: 提示信息
        type: string
    type: object
info:
  contact: {}
paths:
  /sys_api:
    post:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: API基础信息
        in: body
        name: userInfo
        required: true
        schema:
          $ref: '#/definitions/entities.SysApiServiceCreateReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.JsonResponse'
      summary: 创建一条API记录
      tags:
      - API操作
  /sys_api/list:
    post:
      consumes:
      - application/json
      description: 筛选条件请额外
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 分页数据
        in: body
        name: pageReq
        required: true
        schema:
          $ref: '#/definitions/entities.PageReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.JsonResponse'
      summary: 获取api分页数据
      tags:
      - API操作
  /sys_menu:
    get:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 查询菜单列表
      tags:
      - 菜单操作
    post:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 菜单基础信息
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/entities.SysMenuServiceReq'
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 创建一条用户记录
      tags:
      - 菜单操作
  /user:
    post:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户基础信息
        in: body
        name: userInfo
        required: true
        schema:
          $ref: '#/definitions/entities.UserServiceCreateReq'
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 创建一条用户记录
      tags:
      - 用户操作
  /user/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户编号
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 查看用户记录
      tags:
      - 用户操作
    put:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户编号
        in: path
        name: id
        required: true
        type: integer
      - description: 需要更新的用户信息
        in: body
        name: userInfo
        required: true
        schema:
          $ref: '#/definitions/entities.UserServiceUpdateReq'
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 更新用户信息
      tags:
      - 用户操作
  /user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 手机号和密码
        in: body
        name: userInfo
        required: true
        schema:
          $ref: '#/definitions/entities.UserServiceTokenReq'
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 用户授权登录
      tags:
      - 用户操作
  /user/logout:
    post:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 退出会话
      tags:
      - 用户操作
swagger: "2.0"
